# Generated by Django 2.2.5 on 2019-11-09 23:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('shared_logic', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DateNotifications',
        ),
    ]
