# Generated by Django 2.2.5 on 2019-10-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_ID', models.IntegerField(unique=True)),
                ('row', models.IntegerField()),
                ('elevation', models.IntegerField()),
                ('position', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
