# Generated by Django 2.2.5 on 2019-11-06 20:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('cargos_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cell',
            unique_together={('row', 'elevation', 'position', 'storage')},
        ),
    ]
