# Generated by Django 2.2.5 on 2019-10-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos_main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='id',
        ),
        migrations.AlterField(
            model_name='cargo',
            name='cargo_ID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
