# Generated by Django 2.2.5 on 2019-11-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cargos_main', '0003_auto_20191108_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
