# Generated by Django 2.2.5 on 2019-12-12 15:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cargos_main', '0004_storage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='elevations',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='positions',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='rows',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='Droid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('cargo',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cargos_main.Cargo')),
            ],
        ),
    ]
