# Generated by Django 2.2.5 on 2020-01-05 20:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cargos_main', '0005_auto_20191212_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9,
                                      validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='length',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9,
                                      validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='width',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9,
                                      validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cell',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9,
                                      validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cell',
            name='length',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9,
                                      validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='cell',
            name='width',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9,
                                      validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='default_height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9,
                                      validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='default_length',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9,
                                      validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='storage',
            name='default_width',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9,
                                      validators=[django.core.validators.MinValueValidator(1),
                                                  django.core.validators.MaxValueValidator(100)]),
        ),
    ]
