# Generated by Django 2.2.6 on 2020-05-06 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cargos_main', '0007_auto_20200428_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='companies/logos/default.png', upload_to='companies/logos'),
        ),
    ]
