# Generated by Django 2.2.6 on 2020-05-19 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cargos_main', '0008_auto_20200506_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Categorization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_main.Category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cargos_main.Company')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ManyToManyField(through='cargos_main.Categorization', to='cargos_main.Category'),
        ),
    ]
