# Generated by Django 2.2.6 on 2020-05-23 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='users/companies/default-user.png', upload_to='users/images'),
        ),
        migrations.AddField(
            model_name='employee',
            name='social_links',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.SocialNetworks'),
        ),
    ]
