# Generated by Django 2.2.6 on 2020-05-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_auto_20200523_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialnetworks',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
