# Generated by Django 2.2.6 on 2020-05-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_socialnetworks_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='users/images/default-user.png', upload_to='users/images'),
        ),
    ]
