# Generated by Django 2.2.6 on 2020-05-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0007_auto_20200523_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='github',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
